language: node_js
node_js:
- '6.1'
deploy:
  provider: heroku
  skip_cleanup: true
  buildpack: nodejs
  api_key:
    secure: Up9Nsa6rEPncQWjKx0rkcEyoUBg0ga39fIkhNzuYqKbh17GnMTpQbXIV5RvLBWjz5bQ+krS5EHBsO6NGKco0peyTCEMcoePw5Sq22p5I4tLuYvoTwqwGhCZiUTF7UW8pIm0BjYS8OrM1zvxJDaWUuCJlVG8o5D+4x2YvGeKYex2ERjWbIAA4LX/sk1P7OC00OjO4r/ulNINVFkdaU8UxV0dbr63wVKYiW8SGpL+hnTMsB2+USFCLSq8mQD3X9dQy9seGEae68pfmdCTCdW5VKK5TwZPpkiRjF876wSpbMyvuBaoI7sFojYFpfimR/jJXYPNvR0ZpUc+QtJvAyPZrBVyQ9lo/wF//JTNrL+JvkF7bLxmA62RXQyBZFKkYMuRXhXg9JqvPkUCUd4o2IzAayRFGja/j07tbqKrSffcY6OffYdfrkv44j0CKf9pM7OE3RchPwMVdTxQeGbxadHgRg3Dv81BjWj+g8bOpbVQZ+hoysnoU3rr4qZM34bx6dgVrqdMgUd4uPS/ZlgchRQpBtj6TX0jBSgB5o/JgrZFvodID99898E/CWWwt+RY6drTzx2/8lnewZr8KThvEh9ODgIzCS+BscYvugz0yK4Xlhy4nAHO5MsO/9yQEf4PYKUE5P/PqCXv9KcbZ5MxWaTWAsz+J2mj09MTSYbNyDCGos7s=
