language: node_js
node_js:
- '6.1'
deploy:
  provider: heroku
  skip_cleanup: true
  buildpack: nodejs
  api_key:
    secure: OcPenGL3kXbkZ8HMOxBCg9bHGF59Ckgq+/Cdv1/x4zbEKqyoM+F9Awyzdn14voIEm7RpyLdv0VtK6/syWvvOKDd5x3MZiv6fKP5ssaLu6rXz26ah4RR2SibMEOCWaDPMp9wshcBSKxToVsp0MkRSz1V5lmfcp8WweZ1f42wzuMxHgv4KLtDZEI8JO/SKM8XFfjqRPpXSuWgyPVguIO0wxT/V6ETH8xMPySJk2Mz23aEcGISsV8kfysxegubU9li/iHItk9ht+0Zyb3hV99x+9p6HagluFGPwWiKMzNwd8Hg4QI69Cs0sHzO6l+660J6Jh3xA69zAMx7vUOqliExc5awW7Cq57Ahjk3w+T7rgtQHYvpDJRFF7/CG/3huDpuGaFWJS/NCk7FN0Gk3yNOmvqfrdFDh5Vy2PyjmfqBwC+gLIYO2YMbwAOSzwi0nOHCKv2d5AbjrenZM4+Tu2ls46PyJx6Fa4A4zDvasJWySiA+rEkYNvlrfrczgiQumNcq5yl23d8zAVI5h/kiKVg4HkF0Kx6Xtwky8sszRrvYPK7haZtwwc+e338fEaCnKiPwedcWSo+tkCMoxk563w+NQ0y2UNL6BZ5++opdJosW+axR2wbd4/C9+wy0u5zQOkoYCw84MUp9EUdnSfEkWj0TjnLeThEiXzWQkNsOOEiRkMSJI=
